apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simulador-do-caos
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: simulador.google.com
    - http:
        paths:
        - path: /
          backend:
              serviceName: simulador-do-caos
              servicePort: 80
         
