apiVersion: v1
kind: Service
metadata:
  name: simulador-do-caos
spec:
  selector:
    app: simulador-do-caos
  ports:
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
  type: ClusterIP  
