name: ci

on:
  push:
    branches: main

jobs:
  CI:
    runs-on: ubuntu-latest
  
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}       
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags:  |
            alexnnascimento/simulador-do-caos:v3
            alexnnascimento/simulador-do-caos:latest


  CD:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Kubernetes Deployment
        uses: TanmoySG/k-deploy-action@v0.2.2-alpha
        with:
          context: ./manifests
          kubeconfig: ${{ secrets.KUBECONFIG }}
          namespace: default
          manifest: deploy.yaml
          

