name: ci

on:
  push:
    branches: main

jobs:
  CI:
    runs-on: ubuntu-latest
  
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Verificar diretório
        uses: shinhwagk/remote-bash@0.0.1
        run: pwd
      
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags:  |
            alexnnascimento/simulador-do-caos:v2
            alexnnascimento/simulador-do-caos:latest
