name: ci

on:
  push:
    branches: main

jobs:
  CI:
    runs-on: ubuntu-latest
  
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Tag Image 
        id: build-image
        run: |
          # Build a docker container and Tag
          docker build --file ../src/Dockerfile \
          -t alexnnascimento/simulador-do-caos:v2 .  
      -
        name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src/
          file: Dockerfile
          push: true
          tags:  |
            alexnnascimento/simulador-do-caos:v2
            alexnnascimento/simulador-do-caos:latest
